name: Github CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    strategy:
      matrix:
        java_version: [1.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.0.7.7
      - name: Build project
        run: ./gradlew assembleDebug
      - name: Run tests
        run: ./gradlew test
      - name: Run instrumentation tests
        uses: hannesa2/action-android/emulator-run-cmd@0.0.7.7
        with:
          cmd: ./gradlew connectedWithoutVuforiaDebugAndroidTest
          api: 28
          tag: default
          abi: x86
      - name: Save Espresso output
        uses: actions/upload-artifact@master
        if: ${{ always() }}
        with:
          name: Rajawali-Espresso
          path: |
            artifacts/logcat.log
            screenshots/adb/
            ./**/build/reports/**/connected
          if-no-files-found: error
  check:
    name: Check
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.0.7.7
      - name: Gradle checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v2.1.4
        if: ${{ always() }}
        with:
          name: Rajawali-Lint
          path: ./**/build/reports/lint-results.html
